"""modified product model to include owner id

Revision ID: 5b0046990d67
Revises: 94742c83f3f3
Create Date: 2022-12-25 16:58:11.477456

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5b0046990d67'
down_revision = '94742c83f3f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('owner_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'owner_id')
    # ### end Alembic commands ###
