"""restructure usercreate

Revision ID: 7f0ee70b868b
Revises: 1f6b67ed9e87
Create Date: 2022-12-19 12:08:46.123614

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7f0ee70b868b'
down_revision = '1f6b67ed9e87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
