name: Code quality check and endpoint test workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pulling the latest code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2.3.0
        with:
          python-version: '3.10.5'

      - name: cache poetry install
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-1.1.12-0

      - name: Install poetry dependency management
        uses: snok/install-poetry@v1
        with:
          versions: 1.1.12
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: cache deps
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: .venv
          key: pydeps-${{ hashFiles(**/poetry.lock) }}

      - run: poetry install --no-interaction

      - name: Sort all imports according to PEP8 and Flake8
        run: poetry run isort .

      - name: Format code with black
        run: poetry run black .
